### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by nithinbekal** [projectfedena/fedena_v2.1#2]
It seems strange that the license is duplicated in all the source code files. It would make more sense to put it in a LICENSE.md file. Any particular reason why it was decided to add comments in the source files?

**Comment by projectfedena** [comment]
As per Apache Licence, license header should be added to each source file. Please look into the reference at http://www.apache.org/legal/src-headers.html

**Comment by nithinbekal** [comment]
Ok, thanks.

Closing this issue.
