### ISSUE TITLE
rake aborted! undefined method `name' for "actionmailer":String

### ISSUE THREAD

**Issue by Manju244** [projectfedena/fedena_v2.1#3]
While executing the command
rake gems:install

Its showing as,

rake aborted!
undefined method `name' for "actionmailer":String

Tasks: TOP => environment
(See full trace by running task with --trace)

I used RVM to create a custom Ruby 1.8.7 with RubyGems 1.8.10.

And my **\* LOCAL GEMS **\* are 

actionmailer (3.2.2, 2.3.5)
actionpack (3.2.2, 2.3.5)
activemodel (3.2.2)
activerecord (2.3.5)
activeresource (2.3.5)
activesupport (3.2.2, 2.3.5)
arel (3.0.2)
builder (3.0.0)
bundler (1.1.0 ruby)
declarative_authorization (0.5.1)
erubis (2.7.0)
hike (1.2.1)
i18n (0.6.0, 0.4.2)
journey (1.0.3)
json (1.6.5)
mail (2.4.3)
mime-types (1.17.2)
multi_json (1.1.0)
polyglot (0.3.3)
prawn (0.6.3)
prawn-core (0.6.3)
prawn-format (0.2.3)
prawn-layout (0.3.2)
prawn-security (0.1.1)
rack (1.4.1, 1.4.0, 1.0.1)
rack-cache (1.2)
rack-protection (1.1.4)
rack-test (0.6.1)
rails (2.3.5)
rake (0.9.2.2, 0.9.2, 0.8.7)
rdoc (3.12)
redcar (0.11)
require (0.2.7)
rubyzip (0.9.5)
searchlogic (2.4.27)
sinatra (1.3.1)
sprockets (2.1.2)
tilt (1.3.3)
treetop (1.4.10)
tzinfo (0.3.32)
## 

Manjunath

**Comment by jomazzi** [comment]
I also have the same error response while executing the command. My **\* LOCAL GEMS ***

actionmailer (2.3.5)
actionpack (2.3.5)
activerecord (2.3.5)
activeresource (2.3.5)
activesupport (2.3.5)
bigdecimal (1.1.0)
bundle (0.0.1)
bundler (1.6.5)
cgi_multipart_eof_fix (2.5.0)
declarative_authorization (0.5
fattr (2.2.1)
gem_plugin (0.2.3)
hoe (3.12.0)
i18n (0.4.2)
io-console (0.3)
json (1.5.5)
minitest (2.5.1)
mongrel (1.1.5 x86-mingw32)
mysql (2.8.1 x86-mingw32)
prawn (0.6.3)
prawn-core (0.6.3)
prawn-format (0.2.3)
prawn-layout (0.3.2)
prawn-security (0.1.1)
rack (1.0.1)
rails (2.3.5)
rake (0.9.2.2, 0.8.7)
rdoc (3.9.5)
rush (0.6.8)
session (3.1.0)
test-unit (1.2.3)

Please any help on this would be highly appreciated

**Comment by wellington1993** [comment]
See: https://gist.github.com/wellington1993/cbcac9845979fe1eec8253016541a249
